/**
 * Created by Ayush Kulshrestha on 18/09/2019.
 */

export const httpConstants = {
  METHOD_TYPE: {
    POST: "POST",
    PUT: "PUT",
    GET: "GET",
    DELETE: "DELETE",
  },
  CONTENT_TYPE: {
    APPLICATION_JSON: "application/json",
    MULTIPART_FORM_DATA: "multipart/form-data",
    APPLICATION_FORM_URLENCODED: "application/x-www-form-urlencoded",
    IMAGE_PNG: "image/png",
  },
  DEVICE_TYPE: {
    WEB: "web",
  },
  API_END_POINT: {
    REGISTER_DEVICE: "/device",
  },
};

export const stateNamesConstant = {
  andhra: "Andhra Pradesh",
  arunachal: "Arunachal Pradesh",
  assam: "Assam",
  bihar: "Bihar",
  chandigarh: "Chandigarh",
  chhattisgarh: "Chhattisgarh",
  dadra: "Dadra and Nagar Haveli",
  daman: "Daman and Diu",
  delhi: "Delhi",
  goa: "Goa",
  gujarat: "Gujarat",
  haryana: "Haryana",
  himachal: "Himachal",
  jammu: "Jammu",
  jharkhand: "Jharkhand",
  karnataka: "Karnataka",
  kerala: "Kerala",
  lakshadweep: "Lakshadweep",
  madhya: "Madhya Pradesh",
  maharashtra: "Maharashtra",
  manipur: "Manipur",
  meghalaya: "Meghalaya",
  mizoram: "Mizoram",
  nagaland: "Nagaland",
  odisha: "Odisha",
  puducherry: "Puducherry",
  punjab: "Punjab",
  rajasthan: "Rajasthan",
  sikkim: "Sikkim",
  tamil: "Tamil Nadu",
  telangana: "Telangana",
  tripura: "Tripura",
  uttarakhand: "Uttarakhand",
  uttar: "Uttar Pradesh",
  west: "West Bengal",
};

export const DistrictNamesConstant = {
  Anantapur: "Anantapur",
  Chittoor: "Chittoor",
  Eastgodavari: "East Godavari",
  Guntur: "Guntur",
  Kadapa: "Kadapa",
  Krishna: "Krishna",
  Kurnool: "Kurnool",
  Nellore: "Nellore",
  Prakasam: "Prakasam",
  Srikakulam: "Srikakulam",
  Visakhapatnam: "Visakhapatnam",
  Vizianagaram: "Vizianagaram",
  Westgodavari: "West Godavari",
  Anjaw: "Anjaw",
  CentralSiang: "Central Siang",
  Changlang: "Changlang",
  DibangValley: "Dibang Valley",
  EastKameng: "East Kameng",
  EastSiang: "East Siang",
  Kamle: "Kamle",
  KraDaadi: "Kra Daadi",
  KurungKumey: "Kurung Kumey",
  LepaRada: "Lepa Rada",
  Lohit: "Lohit",
  Longding: "Longding",
  LowerDibangValley: "Lower Dibang Valley",
  LowerSiang: "Lower Siang",
  LowerSubansiri: "Lower Subansiri",
  Namsai: "Namsai",
  PakkeKessang: "Pakke Kessang",
  PapumPare: "Papum Pare",
  ShiYomi: "Shi Yomi",
  Tawang: "Tawang",
  Tirap: "Tirap",
  UpperSiang: "Upper Siang",
  UpperSubansiri: "Upper Subansiri",
  WestKameng: "West Kameng",
  WestSiang: "West Siang",
  Bajali: "Bajali",
  Baksa: "Baksa",
  Barpeta: "Barpeta",
  Biswanath: "Biswanath",
  Bongaigaon: "Bongaigaon",
  Cachar: "Cachar",
  Charaideo: "Charaideo",
  Chirang: "Chirang",
  Darrang: "Darrang",
  Dhemaji: "Dhemaji",
  Dhubri: "Dhubri",
  Dibrugarh: "Dibrugarh",
  DimaHasao: "Dima Hasao",
  Goalpara: "Goalpara",
  Golaghat: "Golaghat",
  Hailakandi: "Hailakandi",
  Hojai: "Hojai",
  Jorhat: "Jorhat",
  Kamrup: "Kamrup",
  KamrupMetropolitan: "Kamrup Metropolitan",
  KarbiAnglong: "Karbi Anglong",
  Karimganj: "Karimganj",
  Kokrajhar: "Kokrajhar",
  Lakhimpur: "Lakhimpur",
  Majuli: "Majuli",
  Morigaon: "Morigaon",
  Nagaon: "Nagaon",
  Nalbari: "Nalbari",
  Sivasagar: "Sivasagar",
  Sonitpur: "Sonitpur",
  SouthSalmaraMankachar: "South Salmara-Mankachar",
  Tinsukia: "Tinsukia",
  Udalguri: "Udalguri",
  WestKarbiAnglong: "West Karbi Anglong",
  Araria: "Araria",
  Arwal: "Arwal",
  Aurangabad: "Aurangabad",
  Banka: "Banka",
  Begusarai: "Begusarai",
  Bhagalpur: "Bhagalpur",
  Bhojpur: "Bhojpur",
  Buxar: "Buxar",
  Darbhanga: "Darbhanga",
  EastChamparan: "East Champaran",
  Gaya: "Gaya",
  Gopalganj: "Gopalganj",
  Jamui: "Jamui",
  Jehanabad: "Jehanabad",
  Kaimur: "Kaimur",
  Katihar: "Katihar",
  Khagaria: "Khagaria",
  Kishanganj: "Kishanganj",
  Lakhisarai: "Lakhisarai",
  Madhepura: "Madhepura",
  Madhubani: "Madhubani",
  Munger: "Munger",
  Muzaffarpur: "Muzaffarpur",
  Nalanda: "Nalanda",
  Nawada: "Nawada",
  Patna: "Patna",
  Purnia: "Purnia",
  Rohtas: "Rohtas",
  Saharsa: "Saharsa",
  Samastipur: "Samastipur",
  Saran: "Saran",
  Sheikhpura: "Sheikhpura",
  Sheohar: "Sheohar",
  Sitamarhi: "Sitamarhi",
  Siwan: "Siwan",
  Supaul: "Supaul",
  Vaishali: "Vaishali",
  WestChamparan: "West Champaran",
  Balod: "Balod",
  BalodaBazar: "Baloda Bazar",
  Balrampur: "Balrampur",
  Bastar: "Bastar",
  Bemetara: "Bemetara",
  Bijapur: "Bijapur",
  Bilaspur: "Bilaspur",
  Dantewada: "Dantewada",
  Dhamtari: "Dhamtari",
  Durg: "Durg",
  Gariaband: "Gariaband",
  GaurelaPendraMarwahi: "Gaurela Pendra Marwahi",
  JanjgirChampa: "Janjgir Champa",
  Jashpur: "Jashpur",
  Kabirdham: "Kabirdham",
  Kanker: "Kanker",
  Kondagaon: "Kondagaon",
  Korba: "Korba",
  Koriya: "Koriya",
  Mahasamund: "Mahasamund",
  Mungeli: "Mungeli",
  Narayanpur: "Narayanpur",
  Raigarh: "Raigarh",
  Raipur: "Raipur",
  Rajnandgaon: "Rajnandgaon",
  Sukma: "Sukma",
  Surajpur: "Surajpur",
  Surguja: "Surguja",
  Ahmedabad: "Ahmedabad",
  Amreli: "Amreli",
  Anand: "Anand",
  Aravalli: "Aravalli",
  Banaskantha: "Banaskantha",
  Bharuch: "Bharuch",
  Bhavnagar: "Bhavnagar",
  Botad: "Botad",
  ChhotaUdaipur: "Chhota Udaipur",
  Dahod: "Dahod",
  Dang: "Dang",
  DevbhoomiDwarka: "Devbhoomi Dwarka",
  Gandhinagar: "Gandhinagar",
  GirSomnath: "Gir Somnath",
  Jamnagar: "Jamnagar",
  Junagadh: "Junagadh",
  Kheda: "Kheda",
  Kutch: "Kutch",
  Mahisagar: "Mahisagar",
  Mehsana: "Mehsana",
  Morbi: "Morbi",
  Narmada: "Narmada",
  Navsari: "Navsari",
  Panchmahal: "Panchmahal",
  Patan: "Patan",
  Porbandar: "Porbandar",
  Rajkot: "Rajkot",
  Sabarkantha: "Sabarkantha",
  Surat: "Surat",
  Surendranagar: "Surendranagar",
  Tapi: "Tapi",
  Vadodara: "Vadodara",
  Valsad: "Valsad",
  Ambala: "Ambala",
  Bhiwani: "Bhiwani",
  CharkhiDadri: "Charkhi Dadri",
  Faridabad: "Faridabad",
  Fatehabad: "Fatehabad",
  Gurugram: "Gurugram",
  Hisar: "Hisar",
  Jhajjar: "Jhajjar",
  Jind: "Jind",
  Kaithal: "Kaithal",
  Karnal: "Karnal",
  Kurukshetra: "Kurukshetra",
  Mahendragarh: "Mahendragarh",
  Mewat: "Mewat",
  Palwal: "Palwal",
  Panchkula: "Panchkula",
  Panipat: "Panipat",
  Rewari: "Rewari",
  Rohtak: "Rohtak",
  Sirsa: "Sirsa",
  Sonipat: "Sonipat",
  Yamunanagar: "Yamunanagar",
  Bilaspur: "Bilaspur",
  Chamba: "Chamba",
  Hamirpur: "Hamirpur",
  Kangra: "Kangra",
  Kinnaur: "Kinnaur",
  Kullu: "Kullu",
  LahaulSpiti: "Lahaul Spiti",
  Mandi: "Mandi",
  Shimla: "Shimla",
  Sirmaur: "Sirmaur",
  Solan: "Solan",
  Una: "Una",
  Anantnag: "Anantnag",
  Bandipora: "Bandipora",
  Baramulla: "Baramulla",
  Budgam: "Budgam",
  Doda: "Doda",
  Ganderbal: "Ganderbal",
  Jammu: "Jammu",
  Kathua: "Kathua",
  Kishtwar: "Kishtwar",
  Kulgam: "Kulgam",
  Kupwara: "Kupwara",
  Poonch: "Poonch",
  Pulwama: "Pulwama",
  Rajouri: "Rajouri",
  Ramban: "Ramban",
  Reasi: "Reasi",
  Samba: "Samba",
  Shopian: "Shopian",
  Srinagar: "Srinagar",
  Udhampur: "Udhampur",
  Bokaro: "Bokaro",
  Chatra: "Chatra",
  Deoghar: "Deoghar",
  Dhanbad: "Dhanbad",
  Dumka: "Dumka",
  EastSinghbhum: "East Singhbhum",
  Garhwa: "Garhwa",
  Giridih: "Giridih",
  Godda: "Godda",
  Gumla: "Gumla",
  Hazaribagh: "Hazaribagh",
  Jamtara: "Jamtara",
  Khunti: "Khunti",
  Koderma: "Koderma",
  Latehar: "Latehar",
  Lohardaga: "Lohardaga",
  Pakur: "Pakur",
  Palamu: "Palamu",
  Ramgarh: "Ramgarh",
  Ranchi: "Ranchi",
  Sahebganj: "Sahebganj",
  SeraikelaKharsawan: "Seraikela Kharsawan",
  Simdega: "Simdega",
  WestSinghbhum: "West Singhbhum",
  Bagalkot: "Bagalkot",
  BangaloreRural: "Bangalore Rural",
  BangaloreUrban: "Bangalore Urban",
  Belgaum: "Belgaum",
  Bellary: "Bellary",
  Bidar: "Bidar",
  Chamarajanagar: "Chamarajanagar",
  Chikkaballapur: "Chikkaballapur",
  Chikkamagaluru: "Chikkamagaluru",
  Chitradurga: "Chitradurga",
  DakshinaKannada: "Dakshina Kannada",
  Davanagere: "Davanagere",
  Dharwad: "Dharwad",
  Gadag: "Gadag",
  Gulbarga: "Gulbarga",
  Hassan: "Hassan",
  Haveri: "Haveri",
  Kodagu: "Kodagu",
  Kolar: "Kolar",
  Koppal: "Koppal",
  Mandya: "Mandya",
  Mysore: "Mysore",
  Raichur: "Raichur",
  Ramanagara: "Ramanagara",
  Shimoga: "Shimoga",
  Tumkur: "Tumkur",
  Udupi: "Udupi",
  UttaraKannada: "Uttara Kannada",
  Vijayanagara: "Vijayanagara",
  Vijayapura: "Vijayapura",
  Yadgir: "Yadgir",
  Alappuzha: "Alappuzha",
  Ernakulam: "Ernakulam",
  Idukki: "Idukki",
  Kannur: "Kannur",
  Kasaragod: "Kasaragod",
  Kollam: "Kollam",
  Kottayam: "Kottayam",
  Kozhikode: "Kozhikode",
  Malappuram: "Malappuram",
  Palakkad: "Palakkad",
  Pathanamthitta: "Pathanamthitta",
  Thiruvananthapuram: "Thiruvananthapuram",
  Thrissur: "Thrissur",
  Wayanad: "Wayanad",
  AgarMalwa: "Agar Malwa",
  Alirajpur: "Alirajpur",
  Anuppur: "Anuppur",
  Ashoknagar: "Ashoknagar",
  Balaghat: "Balaghat",
  Barwani: "Barwani",
  Betul: "Betul",
  Bhind: "Bhind",
  Bhopal: "Bhopal",
  Burhanpur: "Burhanpur",
  Chachaura: "Chachaura",
  Chhatarpur: "Chhatarpur",
  Chhindwara: "Chhindwara",
  Damoh: "Damoh",
  Datia: "Datia",
  Dewas: "Dewas",
  Dhar: "Dhar",
  Dindori: "Dindori",
  Guna: "Guna",
  Gwalior: "Gwalior",
  Harda: "Harda",
  Hoshangabad: "Hoshangabad",
  Indore: "Indore",
  Jabalpur: "Jabalpur",
  Jhabua: "Jhabua",
  Katni: "Katni",
  Khandwa: "Khandwa",
  Khargone: "Khargone",
  Maihar: "Maihar",
  Mandla: "Mandla",
  Mandsaur: "Mandsaur",
  Morena: "Morena",
  Nagda: "Nagda",
  Narsinghpur: "Narsinghpur",
  Neemuch: "Neemuch",
  Niwari: "Niwari",
  Panna: "Panna",
  Raisen: "Raisen",
  Rajgarh: "Rajgarh",
  Ratlam: "Ratlam",
  Rewa: "Rewa",
  Sagar: "Sagar",
  Satna: "Satna",
  Sehore: "Sehore",
  Seoni: "Seoni",
  Shahdol: "Shahdol",
  Shajapur: "Shajapur",
  Sheopur: "Sheopur",
  Shivpuri: "Shivpuri",
  Sidhi: "Sidhi",
  Singrauli: "Singrauli",
  Tikamgarh: "Tikamgarh",
  Ujjain: "Ujjain",
  Umaria: "Umaria",
  Vidisha: "Vidisha",
  Ahmednagar: "Ahmednagar",
  Akola: "Akola",
  Amravati: "Amravati",
  Aurangabad: "Aurangabad",
  Beed: "Beed",
  Bhandara: "Bhandara",
  Buldhana: "Buldhana",
  Chandrapur: "Chandrapur",
  Dhule: "Dhule",
  Gadchiroli: "Gadchiroli",
  Gondia: "Gondia",
  Hingoli: "Hingoli",
  Jalgaon: "Jalgaon",
  Jalna: "Jalna",
  Kolhapur: "Kolhapur",
  Latur: "Latur",
  MumbaiCity: "Mumbai City",
  MumbaiSuburban: "Mumbai Suburban",
  Nagpur: "Nagpur",
  Nanded: "Nanded",
  Nandurbar: "Nandurbar",
  Nashik: "Nashik",
  Osmanabad: "Osmanabad",
  Palghar: "Palghar",
  Parbhani: "Parbhani",
  Pune: "Pune",
  Raigad: "Raigad",
  Ratnagiri: "Ratnagiri",
  Sangli: "Sangli",
  Satara: "Satara",
  Sindhudurg: "Sindhudurg",
  Solapur: "Solapur",
  Thane: "Thane",
  Wardha: "Wardha",
  Washim: "Washim",
  Yavatmal: "Yavatmal",
  Bishnupur: "Bishnupur",
  Chandel: "Chandel",
  Churachandpur: "Churachandpur",
  ImphalEast: "Imphal East",
  ImphalWest: "Imphal West",
  Jiribam: "Jiribam",
  Kakching: "Kakching",
  Kamjong: "Kamjong",
  Kangpokpi: "Kangpokpi",
  Noney: "Noney",
  Pherzawl: "Pherzawl",
  Senapati: "Senapati",
  Tamenglong: "Tamenglong",
  Tengnoupal: "Tengnoupal",
  Thoubal: "Thoubal",
  Ukhrul: "Ukhrul",
  EastGaroHills: "East Garo Hills",
  EastJaintiaHills: "East Jaintia Hills",
  EastKhasiHills: "East Khasi Hills",
  NorthGaroHills: "North Garo Hills",
  RiBhoi: "Ri Bhoi",
  SouthGaroHills: "South Garo Hills",
  SouthWestGaroHills: "South West Garo Hills",
  SouthWestKhasiHills: "South West Khasi Hills",
  WestGaroHills: "West Garo Hills",
  WestJaintiaHills: "West Jaintia Hills",
  WestKhasiHills: "West Khasi Hills",
  Aizawl: "Aizawl",
  Champhai: "Champhai",
  Hnahthial: "Hnahthial",
  Kolasib: "Kolasib",
  Khawzawl: "Khawzawl",
  Lawngtlai: "Lawngtlai",
  Lunglei: "Lunglei",
  Mamit: "Mamit",
  Saiha: "Saiha",
  Serchhip: "Serchhip",
  Saitual: "Saitual",
  Dimapur: "Dimapur",
  Kiphire: "Kiphire",
  Kohima: "Kohima",
  Longleng: "Longleng",
  Mokokchung: "Mokokchung",
  Mon: "Mon",
  Noklak: "Noklak",
  Peren: "Peren",
  Phek: "Phek",
  Tuensang: "Tuensang",
  Wokha: "Wokha",
  Zunheboto: "Zunheboto",
  Angul: "Angul",
  Balangir: "Balangir",
  Balasore: "Balasore",
  Bargarh: "Bargarh",
  Bhadrak: "Bhadrak",
  Boudh: "Boudh",
  Cuttack: "Cuttack",
  Debagarh: "Debagarh",
  Dhenkanal: "Dhenkanal",
  Gajapati: "Gajapati",
  Ganjam: "Ganjam",
  Jagatsinghpur: "Jagatsinghpur",
  Jajpur: "Jajpur",
  Jharsuguda: "Jharsuguda",
  Kalahandi: "Kalahandi",
  Kandhamal: "Kandhamal",
  Kendrapara: "Kendrapara",
  Kendujhar: "Kendujhar",
  Khordha: "Khordha",
  Koraput: "Koraput",
  Malkangiri: "Malkangiri",
  Mayurbhanj: "Mayurbhanj",
  Nabarangpur: "Nabarangpur",
  Nayagarh: "Nayagarh",
  Nuapada: "Nuapada",
  Puri: "Puri",
  Rayagada: "Rayagada",
  Sambalpur: "Sambalpur",
  Subarnapur: "Subarnapur",
  Sundergarh: "Sundergarh",
};

export const eventConstants = {
  REGISTER_DEVICE_SUCCESS: "REGISTER_DEVICE_SUCCESS",
  REGISTER_DEVICE_FAILURE: "REGISTER_DEVICE_FAILURE",
};
export const cookiesConstants = {
  DISCLAIMER: "DISCLAIMER",
  DEVICE_ID: "deviceId",
};

export const genericConstants = {
  WEB_COMPONENT_TYPE: {
    STATE: "STATE",
    DISTRICT: "DISTRICT",
    CATEGORY: "CATEGORY",
    CARDS: "CARDS",
  },
};
export const firebaseConfig = {
  apiKey: process.env.REACT_APP_API_KEY,
  authDomain: process.env.REACT_APP_AUTH_DOMAIN,
  databaseURL: process.env.REACT_APP_DATABASE_URL,
  projectId: process.env.REACT_APP_PROJECT_ID,
  storageBucket: process.env.REACT_APP_STORAGE_BUCKET,
  messagingSenderId: process.env.REACT_APP_MESSAGING_SENDER_ID,
  appId: process.env.REACT_APP_APP_ID,
  measurementId: process.env.REACT_APP_MEASUREMENT_ID,
};

export const voteTypeConstants = {
  UP_VOTE: "UP_VOTE",
  DOWN_VOTE: "DOWN_VOTE",
};
